// store/data.js

export const awards = [
  {
    name: "Cybertruck Elongation EVO",
    type: "Tesla",
    project: "by MANSORY",
    label: "ORDER NOW!",
    youtubeId: "ipt3t7WWBR0",
    slug: "cybertruck-elongation-evo",
  },
  {
    name: "2025 Akrapovic GLE 63",
    type: "Mercedes-AMG",
    project: "by GCD",
    label: "ORDER NOW!",
    youtubeId: "6gw6STuVqNA",
    slug: "2025-Akrapovic-GLE-63-Coupe-820",
  },
  {
    name: "2025 Range Rover SV",
    type: "Land Rover",
    project: "by Onyx Concept",
    label: "ORDER NOW!",
    youtubeId: "f7GFuuBjtCs",
    slug: "2025-Range-Rover-SV",
  },
  {
    name: "2024 Range Rover",
    type: "Land Rover",
    project: "by MANSORY",
    label: "ORDER NOW!",
    youtubeId: "ECBuWDufO3Q",
    slug: "2024-Range-Rover",
  },
  {
    name: "2025 Continental GT",
    type: "Bentley",
    project: "by MANSORY",
    label: "ORDER NOW!",
    youtubeId: "nsIQkDB3Yvc",
    slug: "2025-Continental-GT",
  },
  {
    name: "GT 63 S E Performance",
    type: "Mercedes-AMG",
    project: "by MANSORY",
    label: "ORDER NOW!",
    youtubeId: "e9tpY0hxR_A",
    slug: "GT-63-S-E-Performance",
  },
  {
    name: "Aventador Carbonado EVO",
    type: "Lamborghini",
    project: "by MANSORY",
    label: "ORDER NOW!",
    youtubeId: "qft8lwmQzns",
    slug: "Aventador-Carbonado-EVO",
  },
  {
    name: "Range-Rover-Sport-SV",
    type: "Land Rover",
    project: "by MANSORY",
    label: "ORDER NOW!",
    youtubeId: "dZBs3lo93Wk",
    slug: "2024-Range-Rover-Sport-SV",
  },
  {
    name: "P820 EWB Gold Edition",
    type: "Mercedes-AMG",
    project: "by MANSORY",
    label: "ORDER NOW!",
    youtubeId: "ZnRjLvyHU0E",
    slug: "P820-EWB-Gold-Edition",
  },
];